### ISSUE TITLE
Some configuration arguments produce errors

### ISSUE THREAD

**Issue by ahrvojic** [kaiju/docker-gophernicus#1]
Hi Josh, thanks very much for this project! Nicely done.

I noticed some errors are logged when setting the args below:
https://github.com/kaiju/docker-gophernicus/blob/7a5e9574e421d792b37d896ee9948d0591b13c6d/init.sh#L95-L129

I assume your intention was to update `SERVER_ARGS` with `=` instead of `+`?

**Comment by kaiju** [comment]
Apologies, I don't pay a whole lot of attention to this project -- this should be fixed with https://github.com/kaiju/docker-gophernicus/pull/2
